services:
  api:
    image: oven/bun:1
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      CLERK_PUBLISHABLE_KEY: ${CLERK_PUBLISHABLE_KEY}
      CLERK_SECRET_KEY: ${CLERK_SECRET_KEY}
      NEON_PROJECT_ID: ${NEON_PROJECT_ID}
      NEON_API_KEY: ${NEON_API_KEY}
      DATABASE_URL: ${DATABASE_URL}
    restart: unless-stopped
    ports:
      - "3000:3000"